### ISSUE TITLE
Logstash and Filebeat example is not working

### ISSUE THREAD

**Issue by szeestraten** [juju-solutions/layer-logstash#20] opened 2017-07-18 14:59 UTC
Hey guys, trying to deploy an ELK-stack with Filebeats, but the relation between Logstash and Filebeat does not seem to work.

I'm using the example from the [filebeat charm](https://jujucharms.com/filebeat) (see below).
```
juju deploy ~containers/bundle/elk-stack
juju deploy ubuntu
juju deploy ~containers/trusty/filebeat
juju add-relation filebeat:beats-host ubuntu
juju add-relation filebeat logstash
```

Running it, you end up with the following error:
```
zeestrat@devbuntu01:~$ juju deploy ~containers/bundle/elk-stack
Located bundle "cs:~containers/bundle/elk-stack-0"
Deploying charm "cs:trusty/elasticsearch-14"
Deploying charm "cs:trusty/kibana-10"
application kibana exposed
Deploying charm "cs:~containers/trusty/logstash-1"
Deploying charm "cs:trusty/zulu8-2"
Related "zulu8:java" and "logstash:java"
Related "kibana:rest" and "elasticsearch:client"
Related "logstash:elasticsearch" and "elasticsearch:client"
Deploy of bundle completed.
zeestrat@devbuntu01:~$ juju deploy ubuntu
Located charm "cs:ubuntu-10".
Deploying charm "cs:ubuntu-10".
zeestrat@devbuntu01:~$ juju deploy ~containers/trusty/filebeat
Located charm "cs:~containers/filebeat-12".
Deploying charm "cs:~containers/filebeat-12".
zeestrat@devbuntu01:~$ juju add-relation filebeat:beats-host ubuntu
ERROR cannot add relation "filebeat:beats-host ubuntu:juju-info": principal and subordinate applications' series must match
```

Now I understand that the principal and subordinate series must match so I tried to deploy a Xenial series version of Filebeat and relate that to the Ubuntu application which works, but then juju cannot relate Logstash to Filebeat.

```
zeestrat@devbuntu01:~$ juju remove-application filebeat
removing application filebeat
zeestrat@devbuntu01:~$ juju deploy filebeat --series xenial
Located charm "cs:filebeat-6".
Deploying charm "cs:filebeat-6".
zeestrat@devbuntu01:~$ juju add-relation filebeat ubuntu
zeestrat@devbuntu01:~$ juju add-relation filebeat logstash
ERROR cannot add relation "filebeat:beats-host logstash:juju-info": principal and subordinate applications' series must match
zeestrat@devbuntu01:~$ juju add-relation filebeat:logstash logstash                                                                                                                   
ERROR no relations found
zeestrat@devbuntu01:~$ juju add-relation filebeat:logstash logstash:beat
ERROR application "logstash" has no "beat" relation
zeestrat@devbuntu01:~$ juju add-relation filebeat logstash:beat                                                                                                                       
ERROR application "logstash" has no "beat" relation
```

What's the deal?

**Comment by kwmonroe** [comment] 2018-01-31 21:05
I realize this issue is old, but the logstash charm has moved. Bugs and code can be found here:

https://launchpad.net/logstash-charm

With the most recent logstash (rev 2) and filebeat (rev 10), I cannot reproduce this issue:

https://jujucharms.com/logstash/
https://jujucharms.com/filebeat/

I suspect this was fixed when logstash gained xenial support.  If you still have problems, please open a bug here:

https://bugs.launchpad.net/logstash-charm

Closing this out.

**Closed by kwmonroe** 2018-01-31 21:05 UTC
